
[theme]
base="light"

# Primary accent color for interactive elements.
primaryColor = '#273746' # couleur des bouttons

# Background color for the main content area.
backgroundColor= '#F2F3F4' # fond de page

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#D5D8DC'  # sidebar couleur

# Color used for almost all text.
textColor = '#000' # couleur du texte

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"

[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200